development:
  dialect: "sqlite3"
  database: ./blog_development.sqlite

test:
  dialect: "sqlite3"
  database: ./blog_test.sqlite

production:
  dialect: "sqlite3"
  database: ./blog_production.sqlite
